/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List apps */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["AppStatus"][];
                    };
                };
            };
        };
        put?: never;
        /** Register a new app */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["CreateAppRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["AppView"];
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apps/{app_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Overwrite app properties */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    app_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["UpdateAppRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["AppView"];
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Overwrite app properties */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    app_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["UpdateAppRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["AppView"];
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
            };
        };
        trace?: never;
    };
    "/apps/by-name/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find app by name */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["AppView"];
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apps/{app_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get status of app */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    app_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["AppStatus"];
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apps/{app_id}/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    app_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["UserView"][];
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apps/{app_id}/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke user */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    app_id: string;
                    user_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["DeleteUserView"];
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apps/{app_id}/users/{user_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    app_id: string;
                    user_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["UserStatus"];
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apps/{app_id}/users/{user_id}/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get encrypted token */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    app_id: string;
                    user_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["TokenInfo"];
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{app_id}/.well-known/openid-configuration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OIDC discovery */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    app_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Discovery"];
                    };
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{app_id}/oauth/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Start authorization code flow */
        get: {
            parameters: {
                query: {
                    redirect_uri: string;
                    state: string;
                    code_challenge: string;
                    code_challenge_method: string;
                    /**
                     * @description Identifies which end-user account this authorization is for
                     *     (e.g. their email), so that re-authorizing the same account
                     *     later reuses the same user id instead of minting a new one.
                     *     Optional — if omitted, every authorization is treated as a new,
                     *     distinct user.
                     */
                    account_hint?: string;
                    scope?: string;
                };
                header?: never;
                path: {
                    app_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirects the caller's browser on to the app's upstream provider. */
                302: {
                    headers: {
                        LOCATION: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{app_id}/oauth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Callback endpoint */
        get: {
            parameters: {
                query: {
                    code?: string;
                    state: string;
                    error?: string;
                    error_description?: string;
                };
                header?: never;
                path: {
                    app_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /**
                 * @description Redirects back to the caller's own `redirect_uri`, with either
                 *     `code`/`state` on success or `error`/`error_description`/`state` on
                 *     failure — standard RFC 6749 §4.1.2 shape either way.
                 */
                302: {
                    headers: {
                        LOCATION: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{app_id}/oauth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange auth code for token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    app_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": components["schemas"]["TokenRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["TokenResponseBody"];
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["OAuthError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{app_id}/oauth/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke a token (RFC 7009) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    app_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": components["schemas"]["RevokeRequest"];
                };
            };
            responses: {
                /**
                 * @description Per RFC 7009, always 200 — whether or not `token` was recognized —
                 *     so this endpoint can't be used to probe for valid tokens.
                 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppStatus */
        AppStatus: {
            app_id: string;
            name: string;
            /** Format: int64 */
            user_count: number;
            /** Format: int64 */
            active_user_count: number;
            /** Format: int64 */
            needs_reauth_count: number;
        };
        /**
         * AppView
         * @description Never includes `client_secret` — that's write-only through this API.
         *     `public_key` is fine to echo back, since it's public by design.
         */
        AppView: {
            id: string;
            name: string;
            client_id: string;
            auth_url: string;
            token_url: string;
            redirect_url: string;
            allowed_redirect_uris: string[];
            scopes: string;
            token_auth_method: string;
            extra_auth_params: {
                [key: string]: string;
            };
            extra_headers: {
                [key: string]: string;
            };
            public_key: string;
        };
        /** CreateAppRequest */
        CreateAppRequest: {
            name: string;
            client_id: string;
            client_secret: string;
            auth_url: string;
            token_url: string;
            /** @description The redirect URI wowauth registers with the provider. */
            redirect_url: string;
            /**
             * @description Allow-list of redirect URIs the `/oauth/*` facade accepts back from
             *     calling clients.
             * @default []
             */
            allowed_redirect_uris: string[];
            /** @default  */
            scopes: string;
            /** @default basic */
            token_auth_method: string;
            /** @default {} */
            extra_auth_params: {
                [key: string]: string;
            };
            /** @default {} */
            extra_headers: {
                [key: string]: string;
            };
            /**
             * @description X25519 public key, base64-encoded. Tokens returned for this app are
             *     encrypted to this key with HPKE (RFC 9180).
             */
            public_key: string;
        };
        /** DeleteUserView */
        DeleteUserView: {
            id: string;
        };
        /** Discovery */
        Discovery: {
            issuer: string;
            authorization_endpoint: string;
            token_endpoint: string;
            revocation_endpoint: string;
            response_types_supported: string[];
            grant_types_supported: string[];
            code_challenge_methods_supported: string[];
            /**
             * @description wowauth's `/oauth/*` facade treats callers as public clients (PKCE
             *     only, no client secret), the standard model for apps that can't keep
             *     a secret confidential.
             */
            token_endpoint_auth_methods_supported: string[];
        };
        /** OAuthError */
        OAuthError: {
            error: string;
            error_description?: string;
        };
        /** RevokeRequest */
        RevokeRequest: {
            token: string;
            token_type_hint?: string;
        };
        /** TokenInfo */
        TokenInfo: {
            /**
             * @description `base64(HPKE-encapsulated key || ciphertext)`; decrypt with your
             *     private key.
             */
            token: string;
            /** Format: date-time */
            expires_at?: string;
        };
        /** TokenRequest */
        TokenRequest: {
            grant_type: string;
            code?: string;
            redirect_uri?: string;
            code_verifier?: string;
        };
        /** TokenResponseBody */
        TokenResponseBody: {
            access_token: string;
            token_type: string;
            /** Format: int64 */
            expires_in?: number;
            scope?: string;
        };
        /**
         * UpdateAppRequest
         * @description Partial update; every field is optional. Changing `public_key` deletes
         *     every user under this app first — rotating the key invalidates every
         *     grant encrypted under the old one.
         */
        UpdateAppRequest: {
            name?: string;
            client_id?: string;
            client_secret?: string;
            auth_url?: string;
            token_url?: string;
            redirect_url?: string;
            allowed_redirect_uris?: string[];
            scopes?: string;
            token_auth_method?: string;
            extra_auth_params?: {
                [key: string]: string;
            };
            extra_headers?: {
                [key: string]: string;
            };
            public_key?: string;
        };
        /** UserStatus */
        UserStatus: {
            user_id: string;
            status: string;
            /** Format: date-time */
            expires_at?: string;
        };
        /** UserView */
        UserView: {
            user_id: string;
            label?: string;
            scopes: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
